import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const root=process.env.WEB_BUILD_DIR;
const {MemoryRepository}=await import(pathToFileURL(root+'/web/src/application/repository.js'));
const {WebClient}=await import(pathToFileURL(root+'/web/src/application/client.js'));
const {auth}=await import(pathToFileURL(root+'/web/src/application/http.js'));
const id=n=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0'),c=id(3),u=id(1),peer=id(2),session=id(4);
const local=(r,text='hello')=>({conversationId:c,requestId:id(r),senderId:u,content:{kind:'TEXT',text}});
const server=(r,seq,text='hello')=>({...local(r,text),messageId:id(100+r),seq,createdAt:'2026-10-09T09:00:00Z'});
const repo=new MemoryRepository();repo.begin(local(5));repo.fail(c,id(5));repo.begin(local(5));assert.throws(()=>repo.begin(local(5,'changed')));repo.ack(id(5),{...server(5,50n),status:'committed'});assert.equal(repo.after(c),50n);repo.fail(c,id(5));assert.equal(repo.snapshot(c)[0].state,'SENT');
// Starting point is only the current realtime window, never a claim about old history.
repo.realtime(id(8),server(8,52n));assert.equal(repo.after(c),50n);repo.realtime(id(7),server(7,51n));assert.equal(repo.after(c),52n);repo.realtime(id(6),server(6,49n));assert.equal(repo.snapshot(c).length,4);assert.equal(repo.after(c),52n);repo.realtime(id(7),server(7,51n));assert.equal(repo.snapshot(c).length,4);
const before=repo.snapshot(c);assert.throws(()=>repo.page(c,52n,[server(9,53n),server(10,55n)]));assert.deepEqual(repo.snapshot(c),before);repo.page(c,52n,[server(9,53n),server(10,54n)]);assert.equal(repo.after(c),54n);repo.reset();assert.equal(repo.snapshot(c).length,0);assert.equal(repo.hasBaseline(c),false);
repo.begin(local(15));repo.ack(id(15),{...server(15,101n),status:'committed'});repo.realtime(id(13),server(13,99n));assert.equal(repo.after(c),99n);repo.page(c,99n,[server(14,100n),server(15,101n)]);assert.equal(repo.after(c),101n);assert.equal(repo.snapshot(c).filter(m=>m.requestId===id(15)).length,1);repo.reset();
const result={session:{userId:u,sessionId:session,clientType:'WEB',sessionEpoch:1,status:'ACTIVE'},tokens:{accessToken:'controlled-test-access',accessTokenExpiresInSeconds:3600,refreshTokenDelivery:'HTTP_ONLY_SECURE_COOKIE'},replacedExistingSession:false};
assert.throws(()=>auth({...result,tokens:{...result.tokens,refreshToken:'notallowed'}}));assert.throws(()=>auth({...result,session:{...result.session,clientType:'DESKTOP'}}));
const calls=[],sockets=[];let searchResolve,mode='ok',syncCount=0;
function response(p,status=200){return new Response(JSON.stringify(p),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});}
const api=async(url,options)=>{calls.push({url,options});assert.equal(options.cache,'no-store');assert.equal(options.redirect,'error');if(url.includes('/auth/login'))return response(result);if(url.includes('/auth/refresh/web')){assert.equal(JSON.parse(options.body).clientType,'WEB');assert.equal(Object.hasOwn(JSON.parse(options.body),'refreshToken'),false);return response(result);}if(url.includes('/auth/logout'))return new Response(null,{status:204});if(url.includes('/users/me'))return response({user:{userId:u,username:'alice',displayName:'Alice'}});if(url.includes('/users/search'))return new Promise(r=>searchResolve=r);if(url.includes('/friends'))return response({friends:[{user:{userId:peer,username:'bob',displayName:'Bob'},friendshipId:id(6),directConversationId:c}]});if(url.includes('/sync/conversation')){syncCount++;const b=JSON.parse(options.body);if(mode==='bad')return response({garbage:true});return response({syncVersion:'1.0',type:'sync.conversation.page',requestId:b.requestId,conversationId:c,messages:[],hasMore:false});}throw Error('Unexpected contract path');};
const factory=url=>{assert.equal(url,'wss://fixture.invalid/v1/ws');const sock={sent:[],send(raw){this.sent.push(JSON.parse(raw));},close(){this.onclose?.();}};sockets.push(sock);return sock;};
const client=new WebClient('https://fixture.invalid',api,factory,40);await client.login('alice','test-password');await new Promise(r=>setTimeout(r,0));let socket=sockets.at(-1);socket.onopen();const bind=socket.sent[0];assert.equal(bind.type,'auth.bind');assert.deepEqual(Object.keys(bind.payload),['accessToken']);const frame=(type,requestId,payload)=>JSON.stringify({protocolVersion:'1.0',type,requestId,payload});socket.onmessage({data:frame('auth.ack',bind.requestId,{status:'bound',userId:u,sessionId:session,clientType:'WEB',sessionEpoch:1})});client.open(c);await new Promise(r=>setTimeout(r,0));assert.equal(syncCount,0,'No initial history request');
const rid=client.send('uncertain');const sent=socket.sent.at(-1);assert.equal(sent.requestId,rid);await new Promise(r=>setTimeout(r,60));assert.equal(client.repository.snapshot(c)[0].state,'FAILED');assert.equal(syncCount,0);client.retry(c,rid);assert.equal(socket.sent.at(-1).requestId,rid);socket.onmessage({data:frame('message.ack',rid,{status:'committed',conversationId:c,messageId:id(20),seq:100,createdAt:'2026-10-09T09:00:00Z'})});assert.equal(client.repository.snapshot(c)[0].state,'SENT');await new Promise(r=>setTimeout(r,60));assert.equal(client.repository.snapshot(c)[0].state,'SENT');
mode='bad';await client.sync(c);assert.match(client.view().sync,/同步失败/);assert.equal(client.repository.after(c),100n);mode='ok';await client.refresh();assert.equal(client.view().notice,'会话已刷新');const old=socket;const searching=client.search('bob');await client.logout();searchResolve(response({users:[{userId:peer,username:'bob',displayName:'Bob'}]}));await searching;old.onmessage({data:frame('message.created',id(30),{conversationId:c,messageId:id(31),senderId:peer,seq:101,createdAt:'2026-10-09T09:00:00Z',content:{kind:'TEXT',text:'late'}})});assert.equal(client.view().notice,'已退出登录。');assert.equal(client.view().session,false);assert.equal(client.view().searchResults.length,0);assert.equal(client.repository.snapshot(c).length,0);client.dispose();
console.log('PASS Web behavior: exact auth/contracts, no initial backfill, memory state, retry identity, terminal SENT, gap/duplicates/page rollback, refresh/logout and stale callback isolation');

await import('./regressions.mjs');
