import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {fixture,id} from './fixture.mjs';
const playwright=await import(pathToFileURL(process.env.WEB_PLAYWRIGHT_MODULE));const out=process.env.WEB_SCREEN_DIR;await fs.mkdir(out,{recursive:true});
const source=process.env.WEB_CANDIDATE_SHA;if(!/^[a-f0-9]{40}$/.test(source))throw Error('exact candidate SHA required');
const f=await fixture(process.env.WEB_BUILD_DIR,process.env.WEB_CERT_FILE,process.env.WEB_KEY_FILE);const browser=await playwright.chromium.launch({executablePath:process.env.WEB_BROWSER_EXE,headless:true});const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1280,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const entries=[];const narrowSendProof=[];
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function shot(name,steps,send_identity){await page.waitForTimeout(200);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const file=name+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});entries.push({file,sha256:hash(await fs.readFile(path.join(out,file))),candidate_sha:source,page_state:name,steps,...(send_identity?{send_identity}:{}),viewport:page.viewportSize(),appearance:await page.evaluate(()=>({theme:document.documentElement.dataset.theme,fontSize:getComputedStyle(document.documentElement).fontSize,density:document.documentElement.dataset.density})),fixture:'controlled alice/bob/carol; no real account',browser_version:browser.version()});}
async function login(){f.state.mode='ok';await page.getByLabel('用户名',{exact:true}).fill('alice');await page.getByLabel('密码',{exact:true}).fill('controlled-test-password');await page.getByRole('button',{name:'进入工作区'}).click();await page.getByRole('status').filter({hasText:'在线'}).last().waitFor();await page.getByRole('button',{name:'Bob Chen'}).click();}
try {
 await page.goto(f.origin);await shot('login-idle',['navigate built Web HTTPS']);f.state.mode='loginError';await page.getByLabel('用户名',{exact:true}).fill('alice');await page.getByLabel('密码',{exact:true}).fill('controlled-test-password');await page.getByRole('button',{name:'进入工作区'}).click();await page.getByText('账号或密码不正确。',{exact:true}).waitFor();await shot('login-error',['submit controlled wrong authentication']);
 f.state.mode='ok';f.state.delay=700;await page.getByLabel('用户名',{exact:true}).fill('alice');await page.getByLabel('密码',{exact:true}).fill('controlled-test-password');await page.getByRole('button',{name:'进入工作区'}).click();await shot('login-loading',['submit controlled valid login with delay']);f.state.delay=0;await page.getByRole('button',{name:'Bob Chen'}).waitFor();await page.getByRole('button',{name:'Bob Chen'}).click();await shot('chat-empty',['login','open authoritative direct conversation; no prior-history request']);assert.equal(f.state.requests.filter(r=>r.path==='/v1/sync/conversation').length,0);
 f.state.mode='slowAck';await page.getByLabel('消息',{exact:true}).fill('让交流更有空间。');await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByText('SENDING · 发送中',{exact:true}).waitFor();await shot('chat-sending',['send text','controlled durable ACK delayed']);await page.getByText('SENT · 已确认',{exact:true}).waitFor();await shot('chat-sent',['accepted canonical committed ACK']);
 f.state.mode='dropAck';await page.getByLabel('消息',{exact:true}).fill('同一个身份，可靠地重试。');await page.getByRole('button',{name:'发送 ↑'}).click();const original=f.state.sends.at(-1)?.requestId;await page.getByText('FAILED · 未确认',{exact:true}).waitFor({timeout:15000});await shot('chat-failed',['controlled server durable commit but ACK unavailable','wait real send timeout']);f.state.mode='ok';await page.getByRole('button',{name:'重试',exact:true}).click();await page.getByText('SENT · 已确认',{exact:true}).last().waitFor();assert.equal(f.state.sends.at(-1).requestId,original);await shot('chat-retry',['retry same requestId','canonical ACK converges']);
 f.disconnect();await page.getByRole('status').filter({hasText:'连接已断开'}).waitFor();await shot('chat-disconnected',['disconnect controlled WSS']);await page.getByRole('status').filter({hasText:'在线'}).last().waitFor({timeout:10000});await shot('chat-reconnected',['automatic reconnect','same WEB session bind','current-page seq compensation']);
 await page.getByRole('button',{name:'Friends',exact:false}).click();await shot('friends-success',['navigate Friends real list']);f.state.delay=700;await page.getByRole('button',{name:'刷新好友',exact:true}).click();await shot('friends-loading',['refresh friend list delayed']);f.state.delay=0;await page.getByText('正在加载好友…',{exact:true}).waitFor({state:'hidden'});f.state.mode='friendsError';await page.getByRole('button',{name:'刷新好友',exact:true}).click();await page.getByText('好友加载失败，可重试。',{exact:true}).waitFor();await shot('friends-error',['controlled 500 current friend load']);f.state.mode='empty';await page.getByRole('button',{name:'刷新好友',exact:true}).click();await page.getByText('这里等待新的连接',{exact:true}).waitFor();await shot('friends-empty',['authoritative empty friend response']);f.state.mode='ok';await page.getByRole('button',{name:'刷新好友',exact:true}).click();await page.getByLabel('通过准确用户名寻找好友',{exact:true}).fill('missing');await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByText('没有找到该用户名。',{exact:true}).waitFor();await shot('friends-search-empty',['exact normalized username no match']);await page.getByLabel('通过准确用户名寻找好友',{exact:true}).fill('carol');await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByRole('button',{name:'添加好友',exact:true}).waitFor();await shot('friends-search',['exact username carol found']);await page.getByRole('button',{name:'添加好友',exact:true}).click();await page.getByText('好友已添加，唯一私聊已建立',{exact:true}).waitFor();await shot('friends-added',['PUT friend','authoritative friendship/directConversationId','refresh current friend list']);
 for(const p of ['AI','Plugin']){await page.getByRole('button',{name:p,exact:false}).click();await shot(p.toLowerCase()+'-placeholder',['navigate '+p,'honest unavailable capability']);}
 await page.getByRole('button',{name:'Profile',exact:false}).click();await page.getByText('Alice Lin',{exact:true}).waitFor();await shot('profile-success',['GET current user']);f.state.delay=700;await page.getByRole('button',{name:'刷新个人资料'}).click();await shot('profile-loading',['delayed GET current user']);f.state.delay=0;await page.getByText('正在加载个人资料…').waitFor({state:'hidden'});f.state.mode='profileError';await page.getByRole('button',{name:'刷新个人资料'}).click();await page.getByText('个人资料加载失败，可重试。').waitFor();await shot('profile-error',['controlled current profile failure']);f.state.mode='ok';await page.getByRole('button',{name:'刷新个人资料'}).click();await page.getByRole('button',{name:'刷新会话',exact:true}).click();await page.getByText('会话已刷新',{exact:true}).waitFor();await shot('session-refreshed',['HTTP-only secure cookie refresh','same session identity']);
 await page.getByRole('button',{name:'Settings',exact:false}).click();await shot('settings-cold',['default Cold AI 16 comfortable']);await page.getByLabel('字号',{exact:true}).selectOption('20');await page.getByLabel('间距',{exact:true}).selectOption('spacious');await shot('settings-cold-max',['20px','spacious']);await page.getByRole('button',{name:'Warm Creative',exact:false}).click();assert.equal(await page.getByLabel('字号',{exact:true}).inputValue(),'20');assert.equal(await page.getByLabel('间距',{exact:true}).inputValue(),'spacious');await shot('settings-warm-max',['theme only changes colors; independent prefs kept']);for(const p of ['Chat','Friends','AI','Plugin','Profile']){await page.getByRole('button',{name:p,exact:false}).first().click();await shot(p.toLowerCase()+'-warm-max',['Warm Creative','20px spacious',p]);}
 await page.getByRole('button',{name:'Settings',exact:false}).click();await page.getByLabel('字号',{exact:true}).selectOption('14');await page.getByLabel('间距',{exact:true}).selectOption('compact');await shot('settings-warm-min',['14px compact']);await page.reload();await page.getByRole('button',{name:'Settings',exact:false}).click();assert.equal(await page.getByLabel('字号',{exact:true}).inputValue(),'14');await shot('settings-restart',['reload clears business state','appearance persists']);await page.getByRole('button',{name:'Cold AI',exact:false}).click();await shot('settings-cold-min',['cold14 compact']);await page.getByRole('button',{name:'恢复已有会话'}).count().then(()=>{});await page.getByRole('button',{name:'返回登录'}).click();await page.getByRole('button',{name:'恢复已有会话'}).click();await page.getByRole('button',{name:'Bob Chen'}).waitFor();await page.getByRole('button',{name:'Bob Chen'}).click();assert.equal(await page.getByText('让交流更有空间。',{exact:true}).count(),0);await shot('reload-memory-empty',['recover cookie session','no prior messages loaded']);await page.setViewportSize({width:560,height:900});await shot('chat-narrow',['real responsive viewport560x900']);await page.setViewportSize({width:1280,height:900});
 for(const theme of ['cold','warm']){
  await page.getByRole('button',{name:'Settings',exact:false}).click();await page.getByLabel('字号',{exact:true}).selectOption('20');await page.getByLabel('间距',{exact:true}).selectOption('spacious');await page.getByRole('button',{name:theme==='cold'?'Cold AI':'Warm Creative',exact:false}).click();await page.setViewportSize({width:560,height:900});
  await page.getByRole('button',{name:'Chat',exact:false}).first().click();await page.getByRole('button',{name:'Bob Chen'}).click();f.state.mode='slowAck';const text='窄屏中，交流与状态依然清晰。'+theme;const before=f.state.sends.length;const oldSentCount=await page.getByText('SENT · 已确认',{exact:true}).count();if(theme==='warm')assert(oldSentCount>0,'negative control requires an older SENT');await page.getByLabel('消息',{exact:true}).fill(text);await page.getByRole('button',{name:'发送 ↑'}).click();
  const message=page.locator('article.message').filter({has:page.getByText(text,{exact:true})});await message.getByText('SENDING · 发送中',{exact:true}).waitFor();assert.equal(await message.count(),1);assert.equal(await message.getByText('SENT · 已确认',{exact:true}).count(),0,'older SENT must not establish this send as SENT');
  await shot('chat-'+theme+'-narrow-max-sending',['560x900','20px spacious',theme,'specific unique message SENDING; older SENT cannot satisfy'],{text,state:'SENDING'});assert.equal(f.state.sends.length,before+1);const send=f.state.sends.at(-1);assert.equal(send.payload.content.text,text);const committed=f.state.messages.find(m=>m.requestId===send.requestId&&m.conversationId===send.payload.conversationId);assert(committed);const identity={text,requestId:send.requestId,conversationId:send.payload.conversationId,expected_seq:committed.seq};Object.assign(entries.at(-1).send_identity,identity);
  await message.getByText('SENT · 已确认',{exact:true}).waitFor();await message.getByText('#'+committed.seq,{exact:true}).waitFor();assert.equal(await message.getByText('SENDING · 发送中',{exact:true}).count(),0);assert.equal(f.state.sends.at(-1).requestId,identity.requestId);await page.getByLabel('消息',{exact:true}).fill('继续输入，保持可用');await shot('chat-'+theme+'-narrow-max-sent',['same specific message committed ACK status and expected sequence','textarea populated'],{...identity,state:'SENT'});narrowSendProof.push({...identity,theme,old_sent_count:oldSentCount,new_message_initially_sent:false,same_article_sending_to_sent:true,rendered_expected_sequence:true});
  for(const nav of ['Chat','Friends','AI','Plugin','Settings','Profile']){const target=page.getByRole('button',{name:nav,exact:false}).first();await target.scrollIntoViewIfNeeded();assert(await target.isVisible());await target.click();}await page.getByRole('button',{name:'Friends',exact:false}).click();await shot('friends-'+theme+'-narrow-max',['all six host navigation targets clicked','readable search action']);
  f.state.mode='ok';f.state.delay=1100;await page.getByLabel('通过准确用户名寻找好友',{exact:true}).fill('missing');await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByRole('button',{name:'正在处理…',exact:true}).waitFor();const busy=page.getByRole('button',{name:'正在处理…',exact:true});const box=await busy.boundingBox();const dimensions=await busy.evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth,height:e.clientHeight,line:parseFloat(getComputedStyle(e).lineHeight),whiteSpace:getComputedStyle(e).whiteSpace}));assert.equal(dimensions.whiteSpace,'nowrap');assert(dimensions.scroll<=dimensions.client);assert(box.x+box.width<=560);await shot('friends-'+theme+'-narrow-max-busy',['delayed actual search','intact nonshrinking busy label']);f.state.delay=0;await busy.waitFor({state:'hidden'});
  f.state.mode='searchError';await page.getByRole('button',{name:'搜索',exact:true}).click();await page.locator('.search [role=alert]').waitFor();await shot('friends-'+theme+'-narrow-max-error',['actual controlled search error','search retry reachable']);f.state.mode='ok';await page.setViewportSize({width:1280,height:900});
 }
 f.expire();await page.getByText('会话已过期或在其他网页被替换，请重新登录。',{exact:true}).waitFor();await shot('session-expired',['canonical session.revoked','clear account/message memory']);await login();await page.getByRole('button',{name:'退出登录',exact:true}).first().click();await page.getByText('已退出登录。',{exact:true}).waitFor();await shot('session-logout',['server logout revokes cookie','clear memory']);
 assert.deepEqual(errors,[]);const ls=await page.evaluate(()=>Object.keys(localStorage));assert.deepEqual(ls,['plugworldim.appearance.v1']);await fs.writeFile(path.join(out,'manifest.json'),JSON.stringify({task_id:'LOOP1-WEB-001',candidate_sha:source,build_origin:process.env.WEB_BUILD_DIR,build_index_sha256:hash(await fs.readFile(path.join(process.env.WEB_BUILD_DIR,'index.html'))),browser:browser.version(),fixture:'controlled same-origin HTTPS/WSS; self-signed isolated validation context only; no system trust changes',original_unedited_screenshots:true,entries},null,2)+'\n');await fs.writeFile(path.join(out,'protocol-proof.json'),JSON.stringify({narrow_send_identity:narrowSendProof,same_request_retry:true,no_initial_history_request:true,memory_reload_empty:true,secure_cookie_refresh:true,only_appearance_key:true,pageerrors:errors,request_paths:f.state.requests.map(r=>({path:r.path,method:r.method,hasBearer:r.hasBearer})),sends:f.state.sends.map(m=>({requestId:m.requestId,conversationId:m.payload.conversationId}))},null,2)+'\n');console.log('PASS actual browser screenshots '+entries.length);
}catch(error){await shot('failure-diagnostic',['failed executable browser run; not acceptance']);await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({error:String(error),pageerrors:errors,body:await page.locator('body').innerText(),requests:f.state.requests.map(r=>({path:r.path,method:r.method,hasBearer:r.hasBearer}))},null,2)+'\n');throw error;}finally{await browser.close();await f.close();}
