import React,{useState,useEffect,useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import {WebClient} from '../application/client.js';
import {loadAppearance,saveAppearance} from './appearance.js';
import type {Appearance} from './appearance.js';
const client=new WebClient(window.location.origin);
function Logo(){return <img className="logo" src="logo.png" alt="IM+ logo"/>;}
function App(){
  const v=useSyncExternalStore(client.subscribe,client.view);const [page,setPage]=useState('Chat'),[prefs,setPrefs]=useState(loadAppearance),[stored,setStored]=useState(true),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[search,setSearch]=useState(''),[searched,setSearched]=useState(false),[text,setText]=useState('');
  useEffect(()=>{document.documentElement.dataset.theme=prefs.theme;document.documentElement.dataset.density=prefs.density;document.documentElement.style.setProperty('--font-size',prefs.fontSize+'px');},[prefs]);
  useEffect(()=>{if(!v.session){setPage('Chat');setText('');setSearch('');setSearched(false);setUsername('');setPassword('');}},[v.session]);
  function appearance(p:Partial<Appearance>){const next={...prefs,...p};setPrefs(next);setStored(saveAppearance(next));}
  function open(c:string){client.open(c);setPage('Chat');}
  const selected=v.friends.find(f=>f.directConversationId===v.selected),messages=client.repository.snapshot(v.selected);
  return <div className="workspace">
    <aside className="rail"><a className="brand" href="#" onClick={e=>e.preventDefault()}><Logo/><span>IM<span className="brand-plus">+</span><small>PLUGWORLDIM</small></span></a><div className="rail-note">ONLINE WORKSPACE</div><nav aria-label="主导航">{['Chat','Friends','AI','Plugin'].map((p,i)=><button key={p} className={page===p?'nav selected':'nav'} onClick={()=>setPage(p)} disabled={!v.session}><span aria-hidden="true">{['◌','◫','✧','⊞'][i]}</span>{p}<small>{['聊天','好友','未来通信','扩展能力'][i]}</small></button>)}</nav><div className="rail-footer"><button className={page==='Settings'?'nav selected':'nav'} onClick={()=>setPage('Settings')}>⚙ Settings</button>{v.session&&<button className={page==='Profile'?'nav selected':'nav'} onClick={()=>{setPage('Profile');void client.loadProfile();}}>◉ Profile</button>}<p className="tiny">消息仅保留在当前页面<br/>不补聊天历史</p></div></aside>
    <div className="main"><header className="top"><span className="eyebrow">{v.session?'YOUR ONLINE SPACE':'WELCOME TO YOUR WORKSPACE'}</span><div className="top-actions"><span className="connection" role="status">{v.connection}</span>{!v.session&&page==='Settings'&&<button onClick={()=>setPage('Chat')}>返回登录</button>}{v.session&&<button onClick={()=>void client.logout()} disabled={v.authBusy}>退出登录</button>}</div></header>{v.notice&&<div className="notice" role="status">{v.notice}</div>}
    {!v.session&&page!=='Settings'?<section className="login"><div className="welcome"><span className="pill">Adaptive Glass Workspace</span><h1>让交流，<br/><em>更有空间。</em></h1><p>连接此刻的人与想法。<br/>简洁的在线通信，清晰的工作节奏。</p><div className="welcome-art" aria-hidden="true"><div/><div/><span>+</span></div></div><form className="card login-card" onSubmit={e=>{e.preventDefault();const pass=password;setPassword('');void client.login(username,pass);}}><span className="eyebrow">START A CONVERSATION</span><h2>登录构界</h2><p className="muted">消息临时保存在内存，关闭页面后不保留。</p><label>用户名<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} minLength={3} maxLength={64} required disabled={v.authBusy}/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} maxLength={256} required disabled={v.authBusy}/></label><button className="primary" disabled={v.authBusy}>{v.authBusy?'正在登录…':'进入工作区 →'}</button><button type="button" className="link" onClick={()=>void client.refresh()} disabled={v.authBusy}>恢复已有会话</button></form></section>:
    page==='Chat'?<section className="chat-layout"><aside className="conversations"><div className="section-title"><h1>Chat</h1><span>{v.friends.length}</span></div><p className="muted">保持联系，从一句话开始。</p><button className="link" onClick={()=>void client.loadFriends()} disabled={v.friendsBusy}>刷新会话</button>{v.friendsBusy&&<p role="status">正在加载会话…</p>}{v.friendsError&&<p role="alert" className="error">{v.friendsError}</p>}{!v.friendsBusy&&!v.friends.length&&<div className="empty"><span>◌</span><h3>还没有会话</h3><p>在 Friends 搜索并添加好友，<br/>建立唯一私聊。</p><button onClick={()=>setPage('Friends')}>寻找好友</button></div>}{v.friends.map(f=><button key={f.user.userId} className={'conversation '+(v.selected===f.directConversationId?'active':'')} onClick={()=>open(f.directConversationId)}><span className="avatar">{f.user.displayName.slice(0,1)}</span><span><strong>{f.user.displayName}</strong><small>@{f.user.username}</small></span></button>)}</aside><div className="chat-view">{selected?<><div className="chat-heading"><span className="avatar">{selected.user.displayName.slice(0,1)}</span><div><h2>{selected.user.displayName}</h2><p>当前页面的实时消息</p></div><button onClick={()=>client.reconnect()}>重新连接</button></div>{v.sync&&<p className="sync" role="status">{v.sync}</p>}<div className="messages" aria-live="polite">{!messages.length&&<div className="empty"><span>◌</span><h3>从此刻开始</h3><p>这里只展示本页实时消息，不补聊天历史。<br/>发一句问候，开启新的交流。</p></div>}{messages.map(m=><article key={m.requestId} className={'message '+(m.senderId===v.user?.userId?'own':'')}><p>{m.content.text}</p><div className="message-meta"><span>{m.state==='SENDING'?'SENDING · 发送中':m.state==='SENT'?'SENT · 已确认':'FAILED · 未确认'}</span>{m.state==='FAILED'&&<button onClick={()=>client.retry(m.conversationId,m.requestId)}>重试</button>}{m.seq!==undefined&&<span>#{m.seq.toString()}</span>}</div></article>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(text.trim()){client.send(text);setText('');}}}><label className="sr-only" htmlFor="message">消息</label><textarea id="message" placeholder="写一条消息…" value={text} maxLength={4096} onChange={e=>setText(e.target.value)} rows={2}/><button className="primary" disabled={!text.trim()}>发送 ↑</button><small>仅在线内存态 · 未确认消息可使用相同身份重试</small></form></>:<div className="empty chat-empty"><span>◌</span><h2>为有意义的交流留出空间</h2><p>选择左侧会话，开始聊天。</p></div>}</div></section>:
    page==='Friends'?<section className="page"><div className="page-heading"><div><span className="eyebrow">PEOPLE & CONNECTIONS</span><h1>Friends</h1><p className="muted">添加好友，即刻建立双方的唯一私聊。</p></div><button onClick={()=>void client.loadFriends()} disabled={v.friendsBusy}>刷新好友</button></div><form className="search card" onSubmit={e=>{e.preventDefault();setSearched(true);void client.search(search);}}><label htmlFor="search">通过准确用户名寻找好友</label><div><input id="search" placeholder="输入用户名" minLength={3} maxLength={64} value={search} onChange={e=>setSearch(e.target.value)} required/><button className="primary" disabled={v.searchBusy}>{v.searchBusy?'正在处理…':'搜索'}</button></div>{v.searchError&&<p className="error" role="alert">{v.searchError}</p>}{searched&&!v.searchBusy&&!v.searchError&&!v.searchResults.length&&<p>没有找到该用户名。</p>}{v.searchResults.map(u=><div className="friend" key={u.userId}><span className="avatar">{u.displayName.slice(0,1)}</span><div><strong>{u.displayName}</strong><p>@{u.username}</p></div><button disabled={v.searchBusy||u.userId===v.user?.userId||v.friends.some(f=>f.user.userId===u.userId)} onClick={()=>void client.addFriend(u.userId)}>{v.friends.some(f=>f.user.userId===u.userId)?'已是好友':'添加好友'}</button></div>)}</form><h2>我的好友 <span className="muted">{v.friends.length}</span></h2>{v.friendsBusy&&<p role="status">正在加载好友…</p>}{v.friendsError&&<p role="alert" className="error">{v.friendsError}</p>}{!v.friendsBusy&&!v.friends.length&&<div className="card empty"><span>◫</span><h3>这里等待新的连接</h3><p>搜索准确用户名并添加好友。</p></div>}<div className="friend-grid">{v.friends.map(f=><article className="friend card" key={f.user.userId}><span className="avatar">{f.user.displayName.slice(0,1)}</span><div><strong>{f.user.displayName}</strong><p>@{f.user.username}</p></div><button onClick={()=>open(f.directConversationId)}>开始聊天</button></article>)}</div></section>:
    page==='AI'||page==='Plugin'?<section className="page"><span className="eyebrow">{page==='AI'?'FUTURE COMMUNICATION':'PERSONAL CAPABILITIES'}</span><h1>{page}</h1><div className="card placeholder"><div className="placeholder-art" aria-hidden="true">{page==='AI'?'✧':'⊞'}</div><span className="pill">{page==='AI'?'施工中':'当前不可用'}</span><h2>{page==='AI'?'新的想法，正在构建':'你的扩展空间'}</h2><p>{page==='AI'?'AI 通信入口已预留。当前不提供 AI 聊天、工具调用或生成结果。':'当前尚未开放插件能力与已安装清单。此页面没有插件运行、安装或商店功能。'}</p><p className="muted">继续使用 Chat 与 Friends，连接真实的人。</p><button onClick={()=>setPage('Chat')}>返回聊天 →</button></div></section>:
    page==='Settings'?<section className="page settings"><span className="eyebrow">MAKE IT YOURS</span><h1>Settings</h1><p className="muted">外观属于你，交流保持清晰。</p><div className="card"><h2>色彩主题</h2><p>只改变颜色，保留布局、字体和间距。</p><div className="theme-options">{(['cold','warm'] as const).map(t=><button className={prefs.theme===t?'active':''} key={t} onClick={()=>appearance({theme:t})} aria-pressed={prefs.theme===t}><span className={'swatch '+t}/><strong>{t==='cold'?'Cold AI':'Warm Creative'}</strong><small>{t==='cold'?'冷蓝与紫 · 专注的在线空间':'暖色与柔光 · 亲和的交流空间'}</small></button>)}</div><label>字号<select aria-label="字号" value={prefs.fontSize} onChange={e=>appearance({fontSize:Number(e.target.value) as Appearance['fontSize']})}>{[14,16,18,20].map(n=><option key={n} value={n}>{n}px</option>)}</select></label><label>间距<select aria-label="间距" value={prefs.density} onChange={e=>appearance({density:e.target.value as Appearance['density']})}><option value="compact">紧凑</option><option value="comfortable">舒适</option><option value="spacious">宽松</option></select></label><p className="preview">清晰的交流，适合自己的节奏。Aa 123</p><p role="status" className={stored?'muted':'error'}>{stored?'仅主题、字号和间距保存在本地。':'本地外观保存不可用；当前页面仍使用所选外观。'}</p></div></section>:
    <section className="page"><span className="eyebrow">YOUR ACCOUNT</span><h1>Profile</h1><div className="card profile"><button onClick={()=>void client.loadProfile()} disabled={v.profileBusy}>刷新个人资料</button>{v.profileBusy?<p role="status">正在加载个人资料…</p>:v.profileError?<p className="error" role="alert">{v.profileError}</p>:v.user?<><span className="avatar large">{v.user.displayName.slice(0,1)}</span><h2>{v.user.displayName}</h2><p>@{v.user.username}</p></>:<p>暂无个人资料。</p>}<hr/><h3>当前网页会话</h3><p className="muted">刷新凭据由浏览器安全 Cookie 管理；消息和账号数据只保留在内存。</p><button onClick={()=>void client.refresh()} disabled={v.authBusy}>刷新会话</button><button onClick={()=>void client.logout()} disabled={v.authBusy}>退出登录</button></div></section>}
    </div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
