import React,{useEffect,useState,useSyncExternalStore} from "react";
import {createRoot} from "react-dom/client";
import {Workspace} from "../application/ui/workspace.js";
const app=new Workspace();
function UI(){
  const s=useSyncExternalStore(app.observe,app.snapshot),[endpoint,setEndpoint]=useState(s.endpoint),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[query,setQuery]=useState(""),[draft,setDraft]=useState("");
  useEffect(()=>{void app.start();},[]);
  const prefs=s.appearance,friend=s.friends.find(f=>f.directConversationId===s.selected),title=friend?.user.displayName??(s.selected?"Conversation "+s.selected.slice(0,8):"Your conversations");
  const run=(p:Promise<unknown>)=>{void p.catch(()=>{});};
  return <div className={"workspace "+prefs.theme} style={{"--font":prefs.fontSize+"px","--density":prefs.density} as React.CSSProperties}>
    <aside className="rail"><div className="brand" aria-label="IM plus">IM<span>+</span></div><div className="brand-caption">PLUGWORLDIM</div>
      <nav aria-label="Main navigation">{(["Chat","Friends","AI","Plugin"] as const).map((page,i)=><button key={page} className={s.page===page?"nav selected":"nav"} onClick={()=>app.page(page)}><span className="nav-icon" aria-hidden="true">{["◫","♧","✧","⊞"][i]}</span>{page}{page==="AI"&&<small>SOON</small>}</button>)}</nav>
      <div className="rail-bottom"><div className="connection"><span className={"dot "+s.connection}/>{s.connection==="ready"?"Connected":s.connection==="binding"?"Connecting…":"Offline"}</div><button className="nav" onClick={()=>app.page("Settings")}>⚙ Settings</button><div className="identity"><span className="avatar">{s.profile?.displayName[0]??"+"}</span><div><strong>{s.profile?.displayName??"Your workspace"}</strong><small>{s.session?"Personal account":"Sign in to connect"}</small></div></div></div>
    </aside><main>
      <header className="topbar"><div><small className="eyebrow">YOUR CONNECTED WORKSPACE</small><h1>{(s.session||s.offlineAccount||!["Chat","Friends"].includes(s.page))?s.page:"Welcome to IM+"}</h1></div><div className="top-actions"><span className="sync">{s.sync==="syncing"?"Syncing…":s.sync==="failed"?"Sync needs attention":s.connection==="offline"?"Local history":"Up to date"}</span><button className="quiet" onClick={()=>run(app.preferences({...prefs,theme:prefs.theme==="cold"?"warm":"cold"}))}>{prefs.theme==="cold"?"Cold AI":"Warm Creative"}</button></div></header>
      {s.error&&<div className="notice" role="alert"><span>{s.error}</span>{s.session&&<button disabled={!s.session} onClick={()=>run(app.reconnect())}>Reconnect</button>}</div>}
      {(!s.session&&!s.offlineAccount&&["Chat","Friends"].includes(s.page))?<section className="login-layout"><div className="welcome"><div className="orb" aria-hidden="true">✧</div><p className="eyebrow">SPACE FOR EVERY CONVERSATION</p><h2>Stay close.<br/>Think beyond.</h2><p>Conversations, people and a little room for what comes next.</p><div className="feature-row"><span>Account-isolated history</span><span>Secure sign-in</span></div></div><form className="glass login" onSubmit={e=>{e.preventDefault();run(app.login(endpoint,username,password));setPassword("");}}><p className="eyebrow">WELCOME BACK</p><h2>Open your workspace</h2><p className="muted">Sign in to your trusted IM server.</p><label>Server<input type="url" value={endpoint} onChange={e=>setEndpoint(e.target.value)} required/></label><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={s.busy||!s.session}>{s.busy?"Opening workspace…":"Sign in"}</button><button type="button" className="quiet" disabled={s.busy} onClick={()=>run(app.restore(endpoint))}>Resume securely saved session</button><small className="muted">Refresh credentials stay in Windows Credential Manager.</small></form></section>:
      s.page==="Chat"?<section className="chat-layout"><aside className="conversation-list glass"><div className="section-heading"><h2>Messages</h2><button className="quiet" onClick={()=>app.page("Friends")}>New chat</button></div><p className="muted list-caption">People and spaces that matter.</p>{s.conversations.length===0?<div className="empty"><span>◫</span><h3>Your next conversation starts here</h3><p>Add a friend to open a private chat.</p><button onClick={()=>app.page("Friends")}>Find a friend</button></div>:s.conversations.map(id=>{const f=s.friends.find(f=>f.directConversationId===id);return <button key={id} className={s.selected===id?"conversation active":"conversation"} onClick={()=>run(app.open(id))}><span className="avatar">{f?.user.displayName[0]??"#"}</span><div><strong>{f?.user.displayName??"Conversation "+id.slice(0,8)}</strong><small>{s.unavailable.includes(id)?"Access unavailable":"Open local history"}</small></div></button>;})}</aside>
      <div className="chat-pane glass"><div className="chat-heading"><span className="avatar">{friend?.user.displayName[0]??"#"}</span><div><h2>{title}</h2><small>{s.connection==="ready"?"Connected · Messages sync automatically":"Offline · Showing saved history"}</small></div><button className="quiet" disabled={!s.session} onClick={()=>run(app.reconnect())}>Reconnect</button></div><div className="messages" role="log" aria-live="polite">{!s.selected?<div className="empty"><span>✧</span><h3>Good conversations have a place</h3><p>Choose a conversation to begin.</p></div>:s.messages.length===0?<div className="empty"><h3>A fresh start</h3><p>No messages yet. Say hello.</p></div>:s.messages.map((m,i)=><div key={m[0]??m[4]??i} className={m[1]===(s.session?.userId??s.offlineAccount)?"message own":"message"}><div className="bubble">{m[2]}</div><small>{m[6]?new Date(m[6]).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"Now"} · {m[3]==="SENT"?"Sent":m[3]==="SENDING"?"Sending…":"Failed"}{m[3]==="FAILED"&&m[1]===(s.session?.userId??s.offlineAccount)&&m[0]&&<button disabled={!s.session} onClick={()=>run(app.retry(m[0]!))}>Retry</button>}</small></div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(draft.trim()){run(app.send(draft));setDraft("");}}}><label className="sr-only" htmlFor="message">Message</label><textarea id="message" placeholder="Write a message…" value={draft} maxLength={4096} disabled={!s.selected||!s.session} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if(draft.trim()){run(app.send(draft));setDraft("");}}}}/><button className="primary" disabled={!s.selected||!s.session||!draft.trim()}>Send ↑</button></form><p className="composer-help">Enter to send · Shift + Enter for a new line</p></div></section>:
      s.page==="Friends"?<section className="page-content"><div className="glass panel"><p className="eyebrow">BUILD YOUR CIRCLE</p><h2>People, within reach.</h2><p className="muted">Find someone by their exact username.</p><form className="search" onSubmit={e=>{e.preventDefault();run(app.search(query));}}><input aria-label="Search username" value={query} onChange={e=>setQuery(e.target.value)} required/><button className="primary" disabled={s.busy||!s.session}>{s.busy?"Searching…":"Search"}</button></form>{s.results.length===0&&query&&<p className="muted">No matching user shown. Search to check this username.</p>}{s.results.map(u=><div className="person" key={u.userId}><span className="avatar">{u.displayName[0]}</span><div><strong>{u.displayName}</strong><small>@{u.username}</small></div><button disabled={!s.session||u.userId===(s.session?.userId??s.offlineAccount)||s.busy} onClick={()=>run(app.add(u.userId))}>Add friend</button></div>)}</div><div className="glass panel"><h2>Your friends <small>{s.friends.length}</small></h2>{s.friends.length===0?<p className="muted">Your circle is waiting to grow.</p>:s.friends.map(f=><div className="person" key={f.friendshipId}><span className="avatar">{f.user.displayName[0]}</span><div><strong>{f.user.displayName}</strong><small>@{f.user.username}</small></div><button onClick={()=>run(app.open(f.directConversationId))}>Message</button></div>)}</div></section>:
      s.page==="AI"?<section className="page-content"><div className="glass future"><div className="orb">✧</div><p className="eyebrow">A LITTLE ROOM FOR WHAT COMES NEXT</p><h2>Intelligence, in conversation.</h2><p>An AI space is planned for IM+. It is not available in this release.</p><span className="badge">Coming later</span><p className="muted">No AI service is connected. Your conversations are not sent to an AI provider.</p></div></section>:
      s.page==="Plugin"?<section className="page-content"><div className="glass panel"><p className="eyebrow">YOUR WORKSPACE, EXTENDED</p><h2>Plugins</h2><p>Extensions will live here when the plugin platform becomes available.</p><div className="empty"><span>⊞</span><h3>Plugin capabilities unavailable</h3><p>No plugin runtime or installation service is connected in this release.</p></div><span className="badge">Unavailable in Loop 1 S2</span></div></section>:
      <section className="page-content settings"><div className="glass panel"><p className="eyebrow">MAKE ROOM FOR YOURSELF</p><h2>Appearance</h2><p className="muted">Color, type and spacing are independent preferences.</p><fieldset><legend>Color theme</legend><div className="theme-choices">{(["cold","warm"] as const).map(t=><button key={t} className={prefs.theme===t?"theme-choice active":"theme-choice"} aria-pressed={prefs.theme===t} onClick={()=>run(app.preferences({...prefs,theme:t}))}><span className={"swatch "+t}/><strong>{t==="cold"?"Cold AI":"Warm Creative"}</strong><small>{t==="cold"?"Blue · quiet · focused":"Warm · open · expressive"}</small></button>)}</div></fieldset><label>Font size <strong>{prefs.fontSize}px</strong><input type="range" min="14" max="22" step="1" value={prefs.fontSize} onChange={e=>run(app.preferences({...prefs,fontSize:Number(e.target.value)}))}/></label><label>Spacing <strong>{prefs.density===0.8?"Compact":prefs.density===1.2?"Comfortable":"Standard"}</strong><input type="range" min="0.8" max="1.2" step="0.2" value={prefs.density} onChange={e=>run(app.preferences({...prefs,density:Number(e.target.value)}))}/></label><p className="muted">Saved only on this device. Switching themes preserves your type and spacing.</p></div><div className="glass panel"><h2>Profile & session</h2><div className="person"><span className="avatar">{s.profile?.displayName[0]??"+"}</span><div><strong>{s.profile?.displayName??"Profile unavailable"}</strong><small>{s.profile?"@"+s.profile.username:s.session?"Reconnect to load your profile":"Sign in to load your profile"}</small></div></div><div className="button-row"><button disabled={s.busy||(!s.session&&!s.offlineAccount)} onClick={()=>run(app.refresh())}>Refresh session</button><button disabled={!s.session} onClick={()=>app.disconnect()}>Go offline</button><button disabled={!s.session} onClick={()=>run(app.reconnect())}>Reconnect</button><button onClick={()=>run(app.testNotification())}>Test notification</button><button className="danger" disabled={s.busy||(!s.session&&!s.offlineAccount)} onClick={()=>run(app.logout())}>Sign out</button></div><p className="muted">Ctrl + Shift + Space brings your workspace forward. The system tray keeps IM+ within reach.</p></div></section>}
    </main></div>;
}
createRoot(document.getElementById("root")!).render(<UI/>);
