import React,{useEffect,useRef,useState,useSyncExternalStore} from "react";
import {createRoot} from "react-dom/client";
import {Workspace} from "../application/ui/workspace.js";
import {windowControl,windowMaximized} from "../application/ui/native.js";
import {resizedComposerHeight} from "./composer.js";
const app=new Workspace();
function UI(){
  const s=useSyncExternalStore(app.observe,app.snapshot),[registering,setRegistering]=useState(false),[confirmation,setConfirmation]=useState(""),[registered,setRegistered]=useState(false),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[query,setQuery]=useState(""),[draft,setDraft]=useState(""),[maximized,setMaximized]=useState(false);
  const [composerHeight,setComposerHeight]=useState(72),textarea=useRef<HTMLTextAreaElement>(null),resize=useRef<{y:number;height:number}|null>(null);
  useEffect(()=>{void app.start();},[]);
  useEffect(()=>{let active=true;const refresh=()=>{void windowMaximized().then(value=>{if(active)setMaximized(value);}).catch(()=>{});};refresh();window.addEventListener("resize",refresh);return()=>{active=false;window.removeEventListener("resize",refresh);};},[]);
  const prefs=s.appearance,friend=s.friends.find(f=>f.directConversationId===s.selected),title=friend?.user.displayName??(s.selected?"Conversation "+s.selected.slice(0,8):"Your conversations");
  const run=(p:Promise<unknown>)=>{void p.catch(()=>{});};
  const authenticated=!!(s.session||s.offlineAccount);
  return <div className={"app-window "+prefs.theme} style={{"--font":prefs.fontSize+"px","--density":prefs.density} as React.CSSProperties}>
    <div className="window-bar"><div className="window-drag" onPointerDown={e=>{if(e.button===0)run(windowControl("drag"));}} onDoubleClick={()=>run(windowControl("maximize"))}><img src="logo.png" alt=""/><span>IM+ · PlugWorldIM</span></div><div className="window-actions"><button title="Minimize" aria-label="Minimize" onClick={()=>run(windowControl("minimize"))}>−</button><button title={maximized?"Restore":"Maximize"} aria-label={maximized?"Restore":"Maximize"} onClick={()=>run(windowControl("maximize"))}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">{maximized?<><path d="M8 5V4a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1h-1"/><rect x="4" y="7" width="13" height="13" rx="1"/></>:<rect x="5" y="5" width="14" height="14" rx="1"/>}</svg></button><button className="window-close" aria-label="Close" onClick={()=>run(windowControl("close"))}>×</button></div></div>
    <div className={"workspace "+(authenticated?"authenticated":"anonymous")}>
    {authenticated&&<aside className="rail"><div className="brand" aria-label="IM plus"><img src="logo.png" alt="IM+ logo"/>IM<span>+</span></div><div className="brand-caption">PLUGWORLDIM</div>
      <nav aria-label="Main navigation">{(["Chat","Friends","AI","Plugin"] as const).map((page,i)=><button key={page} className={s.page===page?"nav selected":"nav"} onClick={()=>app.page(page)}><span className="nav-icon" aria-hidden="true">{["◫","♧","✧","⊞"][i]}</span>{page}{page==="AI"&&<small>SOON</small>}</button>)}</nav>
      <div className="rail-bottom"><div className="connection" title={s.session?"Signed in":"Viewing local history"}><span className={"dot "+(s.session?"ready":"offline")}/>{s.session?"Online":"Offline"}</div><button className="nav" onClick={()=>app.page("Settings")}>⚙ Settings</button><div className="identity"><span className="avatar">{s.profile?.displayName[0]??"+"}</span><div><strong>{s.profile?.displayName??"Your workspace"}</strong><small>{s.session?"Personal account":"Sign in to connect"}</small></div></div></div>
    </aside>}<main>
      {authenticated&&<header className="topbar"><div><small className="eyebrow">YOUR CONNECTED WORKSPACE</small><h1>{(s.session||s.offlineAccount||!["Chat","Friends"].includes(s.page))?s.page:"Welcome to IM+"}</h1></div><div className="top-actions"><span className="sync">{s.sync==="syncing"?"Syncing…":s.sync==="failed"?"Sync needs attention":s.connection==="offline"?"Local history":"Up to date"}</span><button className="quiet" onClick={()=>run(app.preferences({...prefs,theme:prefs.theme==="cold"?"warm":"cold"}))}>{prefs.theme==="cold"?"Cold AI":"Warm Creative"}</button></div></header>}
      {s.error&&<div className="notice" role="alert"><span>{s.error}</span>{s.session&&<button disabled={!s.session} onClick={()=>run(app.reconnect())}>Reconnect</button>}</div>}
      {!authenticated?<section className="login-layout"><div className="welcome"><img className="login-logo" src="logo.png" alt="IM+ logo"/><p className="eyebrow">SPACE FOR EVERY CONVERSATION</p><h2>Stay close.<br/>Think beyond.</h2><p>Conversations, people and a little room for what comes next.</p></div><form className="glass login" onSubmit={e=>{e.preventDefault();if(registering){run(app.register(username,password,confirmation).then(ok=>{if(ok){setRegistered(true);setRegistering(false);setPassword("");setConfirmation("");}}));}else{run(app.login(s.endpoint,username,password));setPassword("");}}}><p className="eyebrow">{registering?"JOIN IM+":"WELCOME BACK"}</p><h2>{registering?"Create your account":"Open your workspace"}</h2>{registered&&!registering&&<p role="status">Account created. Sign in to continue.</p>}<label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required minLength={registering?3:undefined} maxLength={64} pattern={registering?"[A-Za-z0-9][A-Za-z0-9._-]*":undefined}/></label><label>Password<input type="password" autoComplete={registering?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={registering?12:undefined} maxLength={256}/></label>{registering&&<><label>Confirm password<input type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required maxLength={256}/></label><small>Use 12–256 characters for your password.</small></>}<button className="primary" disabled={s.busy||!username||!password||(registering&&!confirmation)}>{s.busy?"Please wait…":registering?"Create account":"Sign in"}</button><button type="button" className="quiet" disabled={s.busy} onClick={()=>{setRegistering(!registering);setPassword("");setConfirmation("");setRegistered(false);}}>{registering?"Already have an account? Sign in":"New here? Create an account"}</button>{!registering&&<button type="button" className="quiet resume" disabled={s.busy} onClick={()=>run(app.restore(s.endpoint))}>Resume saved session</button>}</form></section>:
      s.page==="Chat"?<section className="chat-layout"><aside className="conversation-list glass"><div className="section-heading"><h2>Messages</h2><button className="quiet" onClick={()=>app.page("Friends")}>New chat</button></div><p className="muted list-caption">People and spaces that matter.</p>{s.conversations.length===0?<div className="empty"><span>◫</span><h3>Your next conversation starts here</h3><p>Add a friend to open a private chat.</p><button onClick={()=>app.page("Friends")}>Find a friend</button></div>:s.conversations.map(id=>{const f=s.friends.find(f=>f.directConversationId===id);return <button key={id} className={s.selected===id?"conversation active":"conversation"} onClick={()=>run(app.open(id))}><span className="avatar">{f?.user.displayName[0]??"#"}</span><div><strong>{f?.user.displayName??"Conversation "+id.slice(0,8)}</strong><small>{s.unavailable.includes(id)?"Access unavailable":s.previews[id]?.text??"No messages yet"}</small></div></button>;})}</aside>
      <div className="chat-pane glass">{s.selected&&<><div className="chat-heading"><span className="avatar">{friend?.user.displayName[0]??"#"}</span><div><h2>{title}</h2><small>{s.connection==="ready"?"Connected · Messages sync automatically":"Offline · Showing saved history"}</small></div><button className="quiet" disabled={!s.session} onClick={()=>run(app.reconnect())}>Reconnect</button></div><div className="messages" role="log" aria-live="polite">{!s.selected?<div className="empty"><span>✧</span><h3>Good conversations have a place</h3><p>Choose a conversation to begin.</p></div>:s.messages.length===0?<div className="empty"><h3>A fresh start</h3><p>No messages yet. Say hello.</p></div>:s.messages.map((m,i)=><div key={m[0]??m[4]??i} className={m[1]===(s.session?.userId??s.offlineAccount)?"message own":"message"}><div className="bubble">{m[2]}</div><small>{m[6]?new Date(m[6]).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"Now"} · {m[3]==="SENT"?"Sent":m[3]==="SENDING"?"Sending…":"Failed"}{m[3]==="FAILED"&&m[1]===(s.session?.userId??s.offlineAccount)&&m[0]&&<button disabled={!s.session} onClick={()=>run(app.retry(m[0]!))}>Retry</button>}</small></div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(draft.trim()){run(app.send(draft));setDraft("");}}}><label className="sr-only" htmlFor="message">Message</label><div className="composer-editor"><textarea ref={textarea} style={{height:composerHeight}} id="message" placeholder="Write a message…" value={draft} maxLength={4096} disabled={!s.selected||!s.session} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if(draft.trim()){run(app.send(draft));setDraft("");}}}}/><button type="button" className="composer-resize" aria-label="Resize message input" title="Drag up to expand" onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();resize.current={y:e.clientY,height:textarea.current?.getBoundingClientRect().height??composerHeight};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(resize.current)setComposerHeight(resizedComposerHeight(resize.current.height,resize.current.y,e.clientY));}} onPointerUp={()=>{resize.current=null;}} onPointerCancel={()=>{resize.current=null;}} onLostPointerCapture={()=>{resize.current=null;}} onKeyDown={e=>{if(e.key==="ArrowUp"||e.key==="ArrowDown"){e.preventDefault();setComposerHeight(value=>resizedComposerHeight(value,0,e.key==="ArrowUp"?-10:10));}}}><svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" aria-hidden="true"><path d="m5 13 8-8m-3 8 3-3"/></svg></button></div><button className="primary" disabled={!s.selected||!s.session||!draft.trim()}>Send ↑</button></form><p className="composer-help">Enter to send · Shift + Enter for a new line</p></>}</div></section>:
      s.page==="Friends"?<section className="page-content"><div className="glass panel"><p className="eyebrow">BUILD YOUR CIRCLE</p><h2>People, within reach.</h2><p className="muted">Find someone by their exact username.</p><form className="search" onSubmit={e=>{e.preventDefault();run(app.search(query));}}><input aria-label="Search username" value={query} onChange={e=>setQuery(e.target.value)} required/><button className="primary" disabled={s.busy||!s.session}>{s.busy?"Searching…":"Search"}</button></form>{s.results.length===0&&query&&<p className="muted">No matching user shown. Search to check this username.</p>}{s.results.map(u=><div className="person" key={u.userId}><span className="avatar">{u.displayName[0]}</span><div><strong>{u.displayName}</strong><small>@{u.username}</small></div><button disabled={!s.session||u.userId===(s.session?.userId??s.offlineAccount)||s.busy} onClick={()=>run(app.add(u.userId))}>Add friend</button></div>)}</div><div className="glass panel"><h2>Your friends <small>{s.friends.length}</small></h2>{s.friends.length===0?<p className="muted">Your circle is waiting to grow.</p>:s.friends.map(f=><div className="person" key={f.friendshipId}><span className="avatar">{f.user.displayName[0]}</span><div><strong>{f.user.displayName}</strong><small>@{f.user.username}</small></div><button onClick={()=>run(app.open(f.directConversationId))}>Message</button></div>)}</div></section>:
      s.page==="AI"?<section className="page-content"><div className="glass future"><div className="orb">✧</div><p className="eyebrow">A LITTLE ROOM FOR WHAT COMES NEXT</p><h2>Intelligence, in conversation.</h2><p>An AI space is planned for IM+. It is not available in this release.</p><span className="badge">Coming later</span><p className="muted">No AI service is connected. Your conversations are not sent to an AI provider.</p></div></section>:
      s.page==="Plugin"?<section className="page-content"><div className="glass panel"><p className="eyebrow">YOUR WORKSPACE, EXTENDED</p><h2>Plugins</h2><p>Extensions will live here when the plugin platform becomes available.</p><div className="empty"><span>⊞</span><h3>Plugin capabilities unavailable</h3><p>No plugin runtime or installation service is connected in this release.</p></div><span className="badge">Unavailable in Loop 1 S2</span></div></section>:
      <section className="page-content settings"><div className="glass panel"><p className="eyebrow">MAKE ROOM FOR YOURSELF</p><h2>Appearance</h2><p className="muted">Color, type and spacing are independent preferences.</p><fieldset><legend>Color theme</legend><div className="theme-choices">{(["cold","warm"] as const).map(t=><button key={t} className={prefs.theme===t?"theme-choice active":"theme-choice"} aria-pressed={prefs.theme===t} onClick={()=>run(app.preferences({...prefs,theme:t}))}><span className={"swatch "+t}/><strong>{t==="cold"?"Cold AI":"Warm Creative"}</strong><small>{t==="cold"?"Blue · quiet · focused":"Warm · open · expressive"}</small></button>)}</div></fieldset><label>Font size <strong>{prefs.fontSize}px</strong><input type="range" min="14" max="22" step="1" value={prefs.fontSize} onChange={e=>run(app.preferences({...prefs,fontSize:Number(e.target.value)}))}/></label><label>Spacing <strong>{prefs.density===0.8?"Compact":prefs.density===1.2?"Comfortable":"Standard"}</strong><input type="range" min="0.8" max="1.2" step="0.2" value={prefs.density} onChange={e=>run(app.preferences({...prefs,density:Number(e.target.value)}))}/></label><p className="muted">Saved only on this device. Switching themes preserves your type and spacing.</p></div><div className="glass panel"><h2>Profile & session</h2><div className="person"><span className="avatar">{s.profile?.displayName[0]??"+"}</span><div><strong>{s.profile?.displayName??"Profile unavailable"}</strong><small>{s.profile?"@"+s.profile.username:s.session?"Reconnect to load your profile":"Sign in to load your profile"}</small></div></div><div className="button-row"><button disabled={s.busy||(!s.session&&!s.offlineAccount)} onClick={()=>run(app.refresh())}>Refresh session</button><button disabled={!s.session} onClick={()=>app.disconnect()}>Go offline</button><button disabled={!s.session} onClick={()=>run(app.reconnect())}>Reconnect</button><button onClick={()=>run(app.testNotification())}>Test notification</button><button className="danger" disabled={s.busy||(!s.session&&!s.offlineAccount)} onClick={()=>run(app.logout())}>Sign out</button></div><p className="muted">Ctrl + Shift + Space brings your workspace forward. The system tray keeps IM+ within reach.</p></div></section>}
    </main></div></div>;
}
createRoot(document.getElementById("root")!).render(<UI/>);
