from pathlib import Path
import json,hashlib
r=Path('H:/.codex/evidence/s1-closure-review');run=r/'research/runs/R-S1-CLOSURE-REVIEW-20261001';events=[json.loads(x) for x in (run/'events.jsonl').read_text().splitlines()];starts={x['data']['command_id']:x['data'] for x in events if x['event_type']=='command_started'};cmd=[]
for x in events:
 if x['event_type']=='command_finished':cmd.append(dict(starts[x['data']['command_id']],**x['data']))
(r/'commands.json').write_text(json.dumps(cmd,indent=2));host=json.loads(sorted(r.glob('hosted-summary-*.json'))[-1].read_text());assert host['result']=='PASS'
report='''# Independent S1 administrative closure review

PASS exact cb2cf431a59e0318a1163073a1c76432135c86d9, bounded 6346f39fc6786bba3cddbde7acc91bbad42446a1..cb2cf431a59e0318a1163073a1c76432135c86d9, original branch recovery/s1-handoff-20261001. Independent /root/s1_closure_review never implemented/fixed candidate. Clean detached checkout H:/.codex/worktrees/s1-closure-review; external evidence only. No candidate writes or services.

283 changed paths restricted to E2E review->done Task, current, S1 Gate checkpoint, own evidence archives/followup. Every pre-existing tracked object except the allowed Task/current transition unchanged (5444 base files). Product, canonical contracts, frozen architecture/PDF, ADRs, historical evidence/FAIL/partial Recorder unchanged. Authority hashes match 83d124bba4b9c605ae29b637e1ea6f8aa55ec4fb7cc6f631f7c069c6f1f77c2e and 546915f639f30cd294f11390da3ade2ce6a85b620bf55727c2a90ca6017d7510.

Four S1 tasks unique done. S1 Gate state justified by independently accepted product6346 full actual-main range, true TLS/live normal/race/contract/fault/source checks and exact previous hosted product acceptance; this administrative range contains no changed product/test/CI implementation. Required named friend403 remains DEFERRED_BY_HUMAN only. S2 explicitly inactive pending new PR5 merge and actual main verification; no S2 implementation. No actionable correctness/security/scope/minimality finding.

Independent checks: clean Recovery Acceptance PASS; frozen architecture34 PASS; sourceall PASS; three archived Recorder validations finished25/30/85 events PASS. Full exact argv/exit/elapsed milliseconds and immutable raw outputs in commands.json and own Recorder blobs. Independent 271 source/worktree/committed archive sizes/SHA256 equal,212 reviewer final-manifest entries valid, final-transport-manifest SHA5e18bcb28c5d6685f61748f8b1cb223fa0b0dd8d9028891ce3e3ce980aa20fba exact. Original605 files sizes/hashes PASS, only prior authorized relocation honored. Original is never claimed clean Acceptance source. No repeated product services for administrative-only delta; actual product replay remains separate independent review6346 evidence.

Direct hosted API push36833725670 exactcb2cf431: classify/architecture/source_go/source_java/gate completedSUCCESS, eight correctly inactiveSKIPPED; independently reproduced classifier6346..head selects only these obligations. PR36833732278 exactcb2cf431: all13 jobs completedSUCCESS (classify,architecture,source_go,source_java,go,java,web,desktop,mobile,shared,compatibility,deploy,gate), full b442acd..head classifier selects all current obligations. Virtual PR5 merge0395b188dc6598541baab2296d3f37dddaa5423f parents exactly[b442acd26777c481620a6bd917863cebfaf79b35,cb2cf431a59e0318a1163073a1c76432135c86d9], tree7d54c2dc83f964dd159a608fbf2d6ec34d414043 equals candidate tree. PR4 independently OPEN/unmerged. Raw direct run/jobs/PR/virtual/candidate API records retained, not aggregate inference.

Failures preserved: preparation Get-FileHash absent in old PowerShell despite aggregate exit0 (corrected via Python hash); own audit first mistook supplied transport SHA for final-manifest filename (only external query corrected); first PR jobs query during running workflow lacked gate, asserted fullset then retainedFAIL and corrected to PENDING model, later all13 actualSUCCESS. Coordinator staging/index-query ordering error remains disclosed in immutable closurefollowup; independent committedbytes verified, no candidate fix. Preparation before Recorder incomplete, prospective_resume/pre_recorder_work true, no full prospective claim.

Own Recorder R-S1-CLOSURE-REVIEW-20261001 finishedPASS46 events and structurally valid. At final inspection own classifier import generated single untracked classify.cpython-312.pyc; original final_state preserves that observation. After finish only this exact reviewer-owned cache removed, final status empty, disclosed post-finish-cleanup.json. Report/commands export/manifest transport generated outside immutable finished trace. Recorder PASS is not product/Stage PASS. No services or resources started. No acceptance of later main merge or S2OPEN candidate.
'''
(r/'independent-review.md').write_text(report,encoding='utf-8');files=[]
for p in sorted(r.rglob('*')):
 if p.is_file() and p.name!='final-manifest.json':
  b=p.read_bytes();files.append({'path':p.relative_to(r).as_posix(),'size':len(b),'sha256':hashlib.sha256(b).hexdigest()})
f=r/'final-manifest.json';f.write_text(json.dumps({'candidate':'cb2cf431a59e0318a1163073a1c76432135c86d9','result':'PASS','files':files,'post_finish_boundary':'report/manifest/export and exact own-cache cleanup outside immutable finished trace'},indent=2));print('PASS manifest',len(files),hashlib.sha256(f.read_bytes()).hexdigest())
